[project]
name = "gvmagdb"
version = "0.1.0"
description = "Genome database with DuckDB backend and bioinformatics search capabilities"
authors = [ "Frederik Schulz <fschulz@lbl.gov>",]
channels = [ "conda-forge", "bioconda",]
platforms = [ "linux-64", "osx-64", "osx-arm64",]

[dependencies]
python = ">=3.10,<3.13"
pip = "*"
duckdb = ">=1.1"
biopython = ">=1.83"
pandas = ">=2.2"
pyarrow = ">=17.0"
linkml = ">=1.8"
linkml-runtime = ">=1.8"
click = ">=8.1"
rich = ">=13.0"
pydantic = ">=2.0"
numpy = ">=1.26"
numba = ">=0.59"
polars = ">=1.0"
diamond = ">=2.1.9"
pyhmmer = ">=0.10"
skani = ">=0.2"
dash = ">=2.17"
dash-bootstrap-components = ">=1.6"
plotly = ">=5.20"

[tasks]
install-package = "python -m pip install -e ."
init-db = "python -m gvmagdb.cli init"
ingest = "python -m gvmagdb.cli ingest"
stats = "python -m gvmagdb.cli stats"
query = "python -m gvmagdb.cli query"
export-faa = "python -m gvmagdb.cli export-faa"
export-fna = "python -m gvmagdb.cli export-fna"
build-diamond = "python -m gvmagdb.cli build-diamond"
search-diamond = "python -m gvmagdb.cli diamond"
search-hmm = "python -m gvmagdb.cli hmmsearch"
extract-hits = "python -m gvmagdb.cli extract"
dashboard = "python -m gvmagdb.analytics.app"
dashboard-cache = "python -m gvmagdb.analytics.cache"
test = "pytest tests/ -v"
test-cov = "pytest tests/ --cov=src/gvmagdb --cov-report=html --cov-report=term"
fmt = "black src/ tests/"
lint = "ruff check src/ tests/"
lint-fix = "ruff check --fix src/ tests/"
typecheck = "mypy src/"
notebook = "jupyter notebook"

[tasks.check]
depends-on = [ "fmt", "lint", "typecheck",]

[environments.default]
solve-group = "default"

[environments.dev]
features = [ "dev",]
solve-group = "default"

[feature.dev.dependencies]
pytest = ">=8.0"
pytest-cov = ">=5.0"
black = ">=24.0"
ruff = ">=0.6"
mypy = ">=1.11"
jupyter = ">=1.0"
ipykernel = ">=6.29"
ipython = ">=8.12"
